# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/overlay/overlay.bd
# Block Designs: The module: 'overlay' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/overlay/ip/overlay_ps_0/overlay_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==overlay_ps_0 || ORIG_REF_NAME==overlay_ps_0} -quiet] -quiet

# IP: bd/overlay/ip/overlay_amix_0/overlay_amix_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==overlay_amix_0 || ORIG_REF_NAME==overlay_amix_0} -quiet] -quiet

# IP: bd/overlay/ip/overlay_ps_axi_periph_0/overlay_ps_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==overlay_ps_axi_periph_0 || ORIG_REF_NAME==overlay_ps_axi_periph_0} -quiet] -quiet

# IP: bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==overlay_rst_ps_50M_0 || ORIG_REF_NAME==overlay_rst_ps_50M_0} -quiet] -quiet

# IP: bd/overlay/ip/overlay_auto_pc_0/overlay_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==overlay_auto_pc_0 || ORIG_REF_NAME==overlay_auto_pc_0} -quiet] -quiet

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/overlay_ooc.xdc
