# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.srcs/sources_1/bd/overlay/ip/overlay_ps_0/overlay_ps_0.xci
# IP: The module: 'overlay_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_ps_0/overlay_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_ps_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.srcs/sources_1/bd/overlay/ip/overlay_ps_0/overlay_ps_0.xci
# IP: The module: 'overlay_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_ps_0/overlay_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_ps_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
