# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.srcs/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0.xci
# IP: The module: 'overlay_rst_ps_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.srcs/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0.xci
# IP: The module: 'overlay_rst_ps_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hk19197/awesomeaudiomixer/rtl-proj/rtl.gen/sources_1/bd/overlay/ip/overlay_rst_ps_50M_0/overlay_rst_ps_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_rst_ps_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
